#!/bin/zsh

normal="#cccccc"
focused="#1793d1"
active="#1763ca"
select="#1793d1"

bspc config normal_border_color         $normal
bspc config active_border_color         $active
bspc config focused_border_color        $focused
bspc config presel_feedback_color       $select
bspc config border_width                1
bspc config window_gap                  0
bspc config top_padding                 18

bspc config split_ratio                 0.618
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config single_monocle              true

bspc rule -a krita desktop='^8' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a st-256color:floating state=floating
bspc rule -a floating:st-256color state=floating
bspc rule -a Pavucontrol state=floating rectangle=780x680

xsetroot -cursor_name left_ptr

pidof -x sxhkd &> /dev/null || sxhkd &
kill-lemonbar.sh; ~/dotfiles/lemonbar/bspwm/bar.zsh &
pidof -x dunst &> /dev/null || dunst &
pidof -x pasystray &> /dev/null || pasystray &
pidof -x compton &> /dev/null || compton -b

autostart.sh
