#!/bin/sh

root=$(git root)
tmpdir=$root/._tmp
mirror=$root/._mirror

set -e

git checkout-index --prefix=$mirror/ -af

git diff-index --cached --name-only --diff-filter=D -z HEAD | \
    (cd $mirror && xargs -0 rm -f --)

rsync -rlpgoD0 -c --size-only --delete --exclude=build/ $mirror/ $tmpdir/

cd $tmpdir
mkdir -p build
cd build
cmake -GNinja ..
nice -n 20 ninja

mannequin/mannequin_test_asan
xix/xix_test_asan

exit 0
