#!/bin/sh

root=$(git root)

exec 1>&2

ninja -C $root/build
if [ $? != 0 ]; then
  exit 1
fi

$root/build/mannequin/mannequin_test_asan
if [ $? != 0 ]; then
  exit 1
fi

$root/build/xix/xix_test_asan
if [ $? != 0 ]; then
  exit 1
fi
